# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  Github:
    url: https://github.com/o7-machinehum
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: Interrupt Labs Homepage

# URL of the Home page image
index_cover: img/home-bg.jpg
# index_cover: img/hardware-F_Cu.svg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: G-JPDQ8MSX3T

# Addthis ID
addthis:

# set your own favicon
favicon: /img/logo.png

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
github_url:
gitlab_url:
linkedin_url:
mailto:


# Mailchimp subscribe modal script
mailchimp_subscribe: https://chimpstatic.com/mcjs-connected/js/users/01e9664f2845368a0228dc20f/5ea24d17f52fd9da86c187722.js
